---
- name: Phase 2 - Server Hardening with iptables
  hosts: all
  become: true
  vars:
    allowed_ports:
      - 80   # HTTP
      - 443  # HTTPS

  tasks:
    ### SSH Hardening ###
    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
      notify: restart sshd

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
      notify: restart sshd

    ### iptables Configuration ###
    - name: Flush existing iptables rules
      iptables:
        flush: true

    - name: Set default policies
      iptables:
        chain: "{{ item.chain }}"
        policy: "{{ item.policy }}"
      loop:
        - { chain: INPUT, policy: DROP }
        - { chain: FORWARD, policy: DROP }
        - { chain: OUTPUT, policy: ACCEPT }

    - name: Allow loopback traffic
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow established connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow ICMP (ping)
      iptables:
        chain: INPUT
        protocol: icmp
        jump: ACCEPT

    - name: Allow essential ports
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
        comment: "Allow {{ item }}/tcp"
      loop: "{{ [new_ssh_port] + allowed_ports }}"

    - name: Save iptables rules persistently
      command: /usr/sbin/netfilter-persistent save
      changed_when: false

    ### System Hardening ###
    - name: Configure sysctl parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: net.ipv4.conf.all.rp_filter, value: 1 }
        - { name: net.ipv4.tcp_syncookies, value: 1 }
        - { name: net.ipv4.conf.all.accept_redirects, value: 0 }

    - name: Install and configure auditd
      apt:
        name: auditd
        state: present

  handlers:
    - name: restart sshd
      service:
        name: ssh
        state: restarted
