- name: Phase 1 - Initial Setup with iptables and SSH port change
  hosts: all
  become: true
  vars:
    current_ssh_port: 22
    new_ssh_port: 19200
    temp_admin_user: "ansible_admin"
    temp_admin_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJGC4GVUTGKdIID2YF5aH6Ky0sJdxD1+m6U7mYkdjAoW"

  tasks:
    ### 1. User Setup ###
    - name: Create temporary admin user
      user:
        name: "{{ temp_admin_user }}"
        groups: sudo
        shell: /bin/bash
        state: present

    - name: Configure passwordless sudo for admin user
      copy:
        dest: /etc/sudoers.d/99-ansible-admin
        content: "{{ temp_admin_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: '/usr/sbin/visudo -cf %s'
        mode: 0440

    - name: Add SSH key for admin user
      ansible.posix.authorized_key:
        user: "{{ temp_admin_user }}"
        state: present
        key: "{{ temp_admin_ssh_key }}"

    ### 2. SSH Configuration ###
    - name: Backup sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: true

    - name: Add new SSH port to sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "Port {{ new_ssh_port }}"
        insertafter: '^#?Port'
        state: present
      notify: restart sshd

    ### 3. iptables Configuration ###
    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present
        update_cache: true

    - name: Allow both SSH ports during transition
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
        comment: "Allow SSH port {{ item }}"
      loop: [ "{{ current_ssh_port }}", "{{ new_ssh_port }}" ]

    - name: Save iptables rules
      command: /usr/sbin/netfilter-persistent save
      changed_when: false

    ### 4. Verification ###
    - name: Wait for new SSH port to be open (from target host)
      wait_for:
        port: "{{ new_ssh_port }}"
        host: "127.0.0.1"
        timeout: 20
        delay: 5
      register: port_check
      until: port_check is succeeded
      retries: 6

    - name: Optional - Test SSH connectivity to new port from control node
      local_action: >
        shell ssh -o StrictHostKeyChecking=no -p {{ new_ssh_port }} {{ temp_admin_user }}@{{ inventory_hostname }} echo success
      register: ssh_test
      until: ssh_test.stdout.find("success") != -1
      retries: 5
      delay: 5

  handlers:
    - name: restart sshd
      service:
        name: ssh
        state: restarted
